import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1773038594357 implements MigrationInterface {
    name = 'InitialSchema1773038594357'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "token" text NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isRevoked" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('ADMIN', 'EMPLOYEE')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "empId" character varying(20), "role" "public"."users_role_enum" NOT NULL DEFAULT 'EMPLOYEE', "isActive" boolean NOT NULL DEFAULT true, "officeLocationRequired" boolean NOT NULL DEFAULT false, "officeLatitude" numeric(10,7), "officeLongitude" numeric(10,7), "officeRadiusMeters" integer, "lastLoginAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_db59e7cc28cb876595e9fb4954a" UNIQUE ("empId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employee_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "department" character varying(100) NOT NULL, "designation" character varying(100) NOT NULL, "employmentType" character varying(50) NOT NULL DEFAULT 'Fresher', "dateOfJoining" date NOT NULL, "reportingManager" character varying(200) NOT NULL, "shiftSchedule" character varying(100) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b52deb77aad7a520ed76f25b902" UNIQUE ("userId"), CONSTRAINT "REL_b52deb77aad7a520ed76f25b90" UNIQUE ("userId"), CONSTRAINT "PK_8481c6a4516f6589b23adf7fefa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "personal_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "aadhaarNumber" character varying(12), "panNumber" character varying(10), "mobileNumber" character varying(15), "whatsappNumber" character varying(15), "bloodGroup" character varying(5), "dateOfBirth" date, "gender" character varying(10), "maritalStatus" character varying(20), "nationality" character varying(50), "currentAddressLine1" character varying(255), "currentCity" character varying(100), "currentState" character varying(100), "currentPincode" character varying(10), "currentCountry" character varying(100), "permanentSameAsCurrent" boolean NOT NULL DEFAULT true, "permanentAddressLine1" character varying(255), "permanentCity" character varying(100), "permanentState" character varying(100), "permanentPincode" character varying(10), "permanentCountry" character varying(100), "emergencyContactNumber" character varying(15), "emergencyContactPerson" character varying(100), "emergencyContactRelationship" character varying(50), "highestQualification" character varying(50), "institutionName" character varying(200), "graduationYear" character varying(10), "totalExperienceYears" character varying(10), "lastCompany" character varying(200), "lastDesignation" character varying(200), "reasonForLeaving" character varying(500), "previousCompanyCTC" character varying(20), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_34a339c814c6e40b25b5f2bc9b2" UNIQUE ("userId"), CONSTRAINT "REL_34a339c814c6e40b25b5f2bc9b" UNIQUE ("userId"), CONSTRAINT "PK_d30ad86a6be960e31aca049615e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "salary_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "ctc" numeric(12,2) NOT NULL DEFAULT '0', "basic" numeric(12,2) NOT NULL DEFAULT '0', "hra" numeric(12,2) NOT NULL DEFAULT '0', "allowances" numeric(12,2) NOT NULL DEFAULT '0', "pfApplicable" boolean NOT NULL DEFAULT true, "pfEmployeeContribution" numeric(12,2) NOT NULL DEFAULT '0', "pfEmployerContribution" numeric(12,2) NOT NULL DEFAULT '0', "taxRegime" character varying(10) NOT NULL DEFAULT 'New', "earnings" jsonb NOT NULL DEFAULT '[]', "deductions" jsonb NOT NULL DEFAULT '[]', "accountNumber" character varying(30), "ifscCode" character varying(20), "bankName" character varying(100), "branchName" character varying(100), "panNumber" character varying(10), "uanNumber" character varying(20), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c9ce129aa6281e0c065259e31ef" UNIQUE ("userId"), CONSTRAINT "REL_c9ce129aa6281e0c065259e31e" UNIQUE ("userId"), CONSTRAINT "PK_60e0d0ef8a920116e46a95b8e50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employee_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "documentType" character varying(50) NOT NULL DEFAULT 'Other', "originalName" character varying(255) NOT NULL, "fileName" character varying(255) NOT NULL, "mimeType" character varying(100) NOT NULL, "size" integer NOT NULL, "filePath" character varying(500) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c19b36f5e604e261fb430293b68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."org_settings_alternatesaturdayoffrule_enum" AS ENUM('NONE', 'SECOND_FOURTH', 'FIRST_THIRD')`);
        await queryRunner.query(`CREATE TABLE "org_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyName" character varying(200) NOT NULL DEFAULT 'HRMS', "companyAddress" text, "workStartTime" TIME NOT NULL DEFAULT '09:00', "workEndTime" TIME NOT NULL DEFAULT '18:00', "lateGraceMinutes" integer NOT NULL DEFAULT '15', "checkInWindowMinutes" integer NOT NULL DEFAULT '10', "halfDayMinMinutes" integer NOT NULL DEFAULT '240', "fullDayMinMinutes" integer NOT NULL DEFAULT '480', "weekOffDays" character varying(100) NOT NULL DEFAULT 'SUNDAY', "alternateSaturdayOffRule" "public"."org_settings_alternatesaturdayoffrule_enum" NOT NULL DEFAULT 'NONE', "officeLatitude" numeric(10,7), "officeLongitude" numeric(10,7), "officeRadiusMeters" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3726dc3a3dfdcd4f0d95b330789" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "holidays" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" date NOT NULL, "name" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3646bdd4c3817d954d830881dfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_status_enum" AS ENUM('PRESENT', 'LATE', 'ABSENT', 'HALF_DAY', 'LEAVE', 'HOLIDAY', 'WEEK_OFF', 'NOT_STARTED', 'MISSED_CHECK_IN')`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employeeId" uuid NOT NULL, "date" date NOT NULL, "firstCheckInAt" TIMESTAMP, "lastCheckOutAt" TIMESTAMP, "totalWorkMinutes" integer NOT NULL DEFAULT '0', "status" "public"."attendance_status_enum" NOT NULL DEFAULT 'ABSENT', "lateMinutes" integer NOT NULL DEFAULT '0', "isManualOverride" boolean NOT NULL DEFAULT false, "overrideReason" character varying(500), "eodDescription" text, "locationValidated" boolean NOT NULL DEFAULT false, "checkInLatitude" numeric(10,7), "checkInLongitude" numeric(10,7), "checkOutLatitude" numeric(10,7), "checkOutLongitude" numeric(10,7), "startWorkOverrideEnabled" boolean NOT NULL DEFAULT false, "overrideValidUntil" TIMESTAMP, "overrideSetBy" uuid, "overrideSetAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9bc37e611804f2566dbb4c85d22" UNIQUE ("employeeId", "date"), CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_punches_type_enum" AS ENUM('CHECK_IN', 'CHECK_OUT')`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_punches_source_enum" AS ENUM('WEB')`);
        await queryRunner.query(`CREATE TABLE "attendance_punches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employeeId" uuid NOT NULL, "type" "public"."attendance_punches_type_enum" NOT NULL, "time" TIMESTAMP NOT NULL, "latitude" numeric(10,7), "longitude" numeric(10,7), "isInsideOffice" boolean NOT NULL DEFAULT false, "source" "public"."attendance_punches_source_enum" NOT NULL DEFAULT 'WEB', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c4fc13ad31e1f9621a66ace368c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "leave_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "probationPeriodMonths" integer NOT NULL DEFAULT '6', "probationLeaveAllowed" boolean NOT NULL DEFAULT false, "allowHalfDayLeave" boolean NOT NULL DEFAULT true, "allowPermissionHours" boolean NOT NULL DEFAULT true, "maxPermissionHoursPerMonth" numeric(4,1) NOT NULL DEFAULT '2', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d3b46bd2974cbb56e3831f3f34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "leave_policy_slabs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "leavePolicyId" uuid NOT NULL, "minYearsOfService" integer NOT NULL, "maxYearsOfService" integer, "casualLeavePerYear" integer NOT NULL DEFAULT '6', "sickLeavePerYear" integer NOT NULL DEFAULT '6', "earnedLeavePerYear" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b49209a1c0d0e6c4114e76c6006" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."leave_requests_leavetype_enum" AS ENUM('CL', 'SL', 'EL', 'LOP', 'PERMISSION')`);
        await queryRunner.query(`CREATE TYPE "public"."leave_requests_requestmode_enum" AS ENUM('FULL_DAY', 'HALF_DAY', 'PERMISSION')`);
        await queryRunner.query(`CREATE TYPE "public"."leave_requests_halfdaysession_enum" AS ENUM('FN', 'AN')`);
        await queryRunner.query(`CREATE TYPE "public"."leave_requests_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "leave_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employeeId" uuid NOT NULL, "leaveType" "public"."leave_requests_leavetype_enum" NOT NULL, "requestMode" "public"."leave_requests_requestmode_enum" NOT NULL, "startDate" date, "endDate" date, "date" date, "halfDaySession" "public"."leave_requests_halfdaysession_enum", "fromTime" TIME, "toTime" TIME, "totalDays" numeric(5,1), "totalHours" numeric(5,2), "reason" text NOT NULL, "adminRemarks" text, "status" "public"."leave_requests_status_enum" NOT NULL DEFAULT 'PENDING', "policySnapshot" jsonb, "approvedBy" uuid, "approvedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d3abcf9a16cef1450129e06fa9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payslip_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payrollRecordId" uuid NOT NULL, "fileName" character varying(255) NOT NULL, "filePath" character varying(500) NOT NULL, "mimeType" character varying(50) NOT NULL DEFAULT 'application/pdf', "generatedAt" TIMESTAMP NOT NULL DEFAULT now(), "emailedAt" TIMESTAMP, CONSTRAINT "UQ_841e5bf7b04da47f7ecfb5aa8af" UNIQUE ("payrollRecordId"), CONSTRAINT "REL_841e5bf7b04da47f7ecfb5aa8a" UNIQUE ("payrollRecordId"), CONSTRAINT "PK_495e6013d95f06cef6dfb969cf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payroll_records_status_enum" AS ENUM('DRAFT', 'GENERATED', 'EMAILED', 'FAILED')`);
        await queryRunner.query(`CREATE TYPE "public"."payroll_records_source_enum" AS ENUM('MANUAL', 'BULK_UPLOAD', 'SYSTEM_AUTO')`);
        await queryRunner.query(`CREATE TABLE "payroll_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payrollRunId" uuid, "employeeId" uuid NOT NULL, "month" integer NOT NULL, "year" integer NOT NULL, "employeeSnapshot" jsonb NOT NULL DEFAULT '{}', "attendanceSnapshot" jsonb NOT NULL DEFAULT '{}', "earnings" jsonb NOT NULL DEFAULT '[]', "deductions" jsonb NOT NULL DEFAULT '[]', "grossEarnings" numeric(12,2) NOT NULL DEFAULT '0', "totalDeductions" numeric(12,2) NOT NULL DEFAULT '0', "netPay" numeric(12,2) NOT NULL DEFAULT '0', "payableDays" numeric(5,1) NOT NULL DEFAULT '0', "workingDays" numeric(5,1) NOT NULL DEFAULT '0', "eligibleWorkingDays" numeric(5,1) NOT NULL DEFAULT '0', "presentDays" numeric(5,1) NOT NULL DEFAULT '0', "leaveDays" numeric(5,1) NOT NULL DEFAULT '0', "lopDays" numeric(5,1) NOT NULL DEFAULT '0', "status" "public"."payroll_records_status_enum" NOT NULL DEFAULT 'DRAFT', "source" "public"."payroll_records_source_enum" NOT NULL DEFAULT 'MANUAL', "remarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_869cabe268deb5726e742f2d3f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payroll_runs_status_enum" AS ENUM('DRAFT', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL_SUCCESS')`);
        await queryRunner.query(`CREATE TABLE "payroll_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "month" integer NOT NULL, "year" integer NOT NULL, "status" "public"."payroll_runs_status_enum" NOT NULL DEFAULT 'DRAFT', "totalEmployees" integer NOT NULL DEFAULT '0', "successCount" integer NOT NULL DEFAULT '0', "failedCount" integer NOT NULL DEFAULT '0', "createdBy" uuid, "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6049f42c972640c0eb99ba8035e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payroll_import_jobs_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL_SUCCESS')`);
        await queryRunner.query(`CREATE TABLE "payroll_import_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payrollRunId" uuid NOT NULL, "originalFileName" character varying(255) NOT NULL, "filePath" character varying(500) NOT NULL, "totalRows" integer NOT NULL DEFAULT '0', "processedRows" integer NOT NULL DEFAULT '0', "successRows" integer NOT NULL DEFAULT '0', "failedRows" integer NOT NULL DEFAULT '0', "status" "public"."payroll_import_jobs_status_enum" NOT NULL DEFAULT 'PENDING', "progressPercentage" integer NOT NULL DEFAULT '0', "errorSummary" jsonb NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a06b6dfb2476c18e10c6ba0424b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_profiles" ADD CONSTRAINT "FK_b52deb77aad7a520ed76f25b902" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal_details" ADD CONSTRAINT "FK_34a339c814c6e40b25b5f2bc9b2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_details" ADD CONSTRAINT "FK_c9ce129aa6281e0c065259e31ef" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_documents" ADD CONSTRAINT "FK_ad63e9df812f16bc351ae35e683" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_07731c02b0333dc9b2678f98213" FOREIGN KEY ("employeeId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_punches" ADD CONSTRAINT "FK_d5397b620dfd25b9262dcb4b1eb" FOREIGN KEY ("employeeId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policy_slabs" ADD CONSTRAINT "FK_b89e20927fac185468e0227ad6b" FOREIGN KEY ("leavePolicyId") REFERENCES "leave_policies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payslip_documents" ADD CONSTRAINT "FK_841e5bf7b04da47f7ecfb5aa8af" FOREIGN KEY ("payrollRecordId") REFERENCES "payroll_records"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payroll_records" ADD CONSTRAINT "FK_58aec9632e8a64076b21bdf3b79" FOREIGN KEY ("payrollRunId") REFERENCES "payroll_runs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payroll_import_jobs" ADD CONSTRAINT "FK_46bb8d5fee2e44ee30d6e86a71f" FOREIGN KEY ("payrollRunId") REFERENCES "payroll_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payroll_import_jobs" DROP CONSTRAINT "FK_46bb8d5fee2e44ee30d6e86a71f"`);
        await queryRunner.query(`ALTER TABLE "payroll_records" DROP CONSTRAINT "FK_58aec9632e8a64076b21bdf3b79"`);
        await queryRunner.query(`ALTER TABLE "payslip_documents" DROP CONSTRAINT "FK_841e5bf7b04da47f7ecfb5aa8af"`);
        await queryRunner.query(`ALTER TABLE "leave_policy_slabs" DROP CONSTRAINT "FK_b89e20927fac185468e0227ad6b"`);
        await queryRunner.query(`ALTER TABLE "attendance_punches" DROP CONSTRAINT "FK_d5397b620dfd25b9262dcb4b1eb"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_07731c02b0333dc9b2678f98213"`);
        await queryRunner.query(`ALTER TABLE "employee_documents" DROP CONSTRAINT "FK_ad63e9df812f16bc351ae35e683"`);
        await queryRunner.query(`ALTER TABLE "salary_details" DROP CONSTRAINT "FK_c9ce129aa6281e0c065259e31ef"`);
        await queryRunner.query(`ALTER TABLE "personal_details" DROP CONSTRAINT "FK_34a339c814c6e40b25b5f2bc9b2"`);
        await queryRunner.query(`ALTER TABLE "employee_profiles" DROP CONSTRAINT "FK_b52deb77aad7a520ed76f25b902"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`DROP TABLE "payroll_import_jobs"`);
        await queryRunner.query(`DROP TYPE "public"."payroll_import_jobs_status_enum"`);
        await queryRunner.query(`DROP TABLE "payroll_runs"`);
        await queryRunner.query(`DROP TYPE "public"."payroll_runs_status_enum"`);
        await queryRunner.query(`DROP TABLE "payroll_records"`);
        await queryRunner.query(`DROP TYPE "public"."payroll_records_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payroll_records_status_enum"`);
        await queryRunner.query(`DROP TABLE "payslip_documents"`);
        await queryRunner.query(`DROP TABLE "leave_requests"`);
        await queryRunner.query(`DROP TYPE "public"."leave_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leave_requests_halfdaysession_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leave_requests_requestmode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leave_requests_leavetype_enum"`);
        await queryRunner.query(`DROP TABLE "leave_policy_slabs"`);
        await queryRunner.query(`DROP TABLE "leave_policies"`);
        await queryRunner.query(`DROP TABLE "attendance_punches"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_punches_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_punches_type_enum"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_status_enum"`);
        await queryRunner.query(`DROP TABLE "holidays"`);
        await queryRunner.query(`DROP TABLE "org_settings"`);
        await queryRunner.query(`DROP TYPE "public"."org_settings_alternatesaturdayoffrule_enum"`);
        await queryRunner.query(`DROP TABLE "employee_documents"`);
        await queryRunner.query(`DROP TABLE "salary_details"`);
        await queryRunner.query(`DROP TABLE "personal_details"`);
        await queryRunner.query(`DROP TABLE "employee_profiles"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
    }

}
