import { z } from 'zod';

export const savePersonalSchema = z.object({
  aadhaarNumber: z.string().max(12).optional().default(''),
  panNumber: z.string().max(10).optional().default(''),
  mobileNumber: z.string().max(15).optional().default(''),
  whatsappNumber: z.string().max(15).optional().default(''),
  bloodGroup: z.string().max(5).optional().default(''),
  dateOfBirth: z.string().optional().default(''),
  gender: z.string().max(10).optional().default(''),
  maritalStatus: z.string().max(20).optional().default(''),
  nationality: z.string().max(50).optional().default(''),
  currentAddressLine1: z.string().max(255).optional().default(''),
  currentCity: z.string().max(100).optional().default(''),
  currentState: z.string().max(100).optional().default(''),
  currentPincode: z.string().max(10).optional().default(''),
  currentCountry: z.string().max(100).optional().default(''),
  permanentSameAsCurrent: z.boolean().optional().default(true),
  permanentAddressLine1: z.string().max(255).optional().default(''),
  permanentCity: z.string().max(100).optional().default(''),
  permanentState: z.string().max(100).optional().default(''),
  permanentPincode: z.string().max(10).optional().default(''),
  permanentCountry: z.string().max(100).optional().default(''),
  emergencyContactNumber: z.string().max(15).optional().default(''),
  emergencyContactPerson: z.string().max(100).optional().default(''),
  emergencyContactRelationship: z.string().max(50).optional().default(''),
  highestQualification: z.string().max(50).optional().default(''),
  institutionName: z.string().max(200).optional().default(''),
  graduationYear: z.string().max(10).optional().default(''),
  totalExperienceYears: z.string().max(10).optional().default(''),
  lastCompany: z.string().max(200).optional().default(''),
  lastDesignation: z.string().max(200).optional().default(''),
  reasonForLeaving: z.string().max(500).optional().default(''),
  previousCompanyCTC: z.string().max(20).optional().default(''),
});
