import {
  EsiWageBasis,
  PfWageBasis,
  PtCalculationMode,
  RoundingRule,
  SalaryCalculationType,
  SalaryComponentCategory,
  SalaryComponentSourceType,
  SalaryComponentStatus,
  StatutoryCalculationMode,
} from './salary.enums';
import { OrganizationSalaryConfigInput } from './salary.types';

export const buildDefaultSalaryConfig = (): OrganizationSalaryConfigInput => {
  const today = new Date().toISOString().slice(0, 10);

  return {
    defaultTemplateName: 'Default CTC Split Template',
    effectiveFrom: today,
    taxRegimeDefaults: 'New',
    metadata: {
      preset: 'excel-migration-default',
      description: 'Default preset migrated from existing Excel salary rules.',
    },
    roundingRules: {
      componentRule: RoundingRule.ROUND,
      statutoryRule: RoundingRule.ROUND,
      summaryRule: RoundingRule.ROUND,
    },
    pfConfig: {
      pfApplicable: true,
      pfCalculationMode: StatutoryCalculationMode.PERCENTAGE,
      pfWageBasis: PfWageBasis.BASIC,
      pfCustomComponentCodes: [],
      employeePfRate: 12,
      employerPfRate: 12,
      pensionRate: 8.33,
      employeePfFixedAmount: 0,
      employerPfFixedAmount: 0,
      pensionFixedAmount: 0,
      pfWageLimitEnabled: true,
      pfWageLimitAmount: 15000,
      allowHigherPf: false,
      roundOffRule: RoundingRule.ROUND,
      editablePerEmployee: true,
      defaultEnabled: true,
    },
    esiConfig: {
      esiApplicable: true,
      esiCalculationMode: StatutoryCalculationMode.PERCENTAGE,
      employeeEsiRate: 0.75,
      employerEsiRate: 3.25,
      employeeEsiFixedAmount: 0,
      employerEsiFixedAmount: 0,
      esiWageBasis: EsiWageBasis.GROSS,
      esiCustomComponentCodes: [],
      esiEligibilityThresholdEnabled: true,
      esiEligibilityThresholdAmount: 21000,
      roundOffRule: RoundingRule.ROUND,
      editablePerEmployee: true,
      defaultEnabled: true,
    },
    ptConfig: {
      ptApplicable: true,
      ptCalculationMode: PtCalculationMode.FIXED,
      fixedAmount: 200,
      slabs: [],
      editablePerEmployee: true,
      defaultEnabled: true,
    },
    components: [
      {
        componentName: 'Basic',
        componentCode: 'BASIC',
        category: SalaryComponentCategory.EARNING,
        sourceType: SalaryComponentSourceType.TEMPLATE_DEFAULT,
        status: SalaryComponentStatus.ACTIVE,
        defaultEnabled: true,
        calculationType: SalaryCalculationType.PERCENTAGE,
        value: 50,
        percentageOf: 'MONTHLY_CTC',
        formulaExpression: null,
        taxable: true,
        includeInPfWage: true,
        includeInEsiWage: true,
        includeInGross: true,
        affectsNetPay: false,
        editableForEmployee: true,
        displayOrder: 1,
      },
      {
        componentName: 'HRA',
        componentCode: 'HRA',
        category: SalaryComponentCategory.EARNING,
        sourceType: SalaryComponentSourceType.TEMPLATE_DEFAULT,
        status: SalaryComponentStatus.ACTIVE,
        defaultEnabled: true,
        calculationType: SalaryCalculationType.PERCENTAGE,
        value: 40,
        percentageOf: 'BASIC',
        formulaExpression: null,
        taxable: true,
        includeInPfWage: false,
        includeInEsiWage: true,
        includeInGross: true,
        affectsNetPay: false,
        editableForEmployee: true,
        displayOrder: 2,
      },
      {
        componentName: 'Special Allowance',
        componentCode: 'SPECIAL_ALLOWANCE',
        category: SalaryComponentCategory.EARNING,
        sourceType: SalaryComponentSourceType.TEMPLATE_DEFAULT,
        status: SalaryComponentStatus.ACTIVE,
        defaultEnabled: true,
        calculationType: SalaryCalculationType.RESIDUAL,
        value: null,
        percentageOf: 'MONTHLY_CTC',
        formulaExpression: null,
        taxable: true,
        includeInPfWage: false,
        includeInEsiWage: true,
        includeInGross: true,
        affectsNetPay: false,
        editableForEmployee: true,
        displayOrder: 3,
      },
      {
        componentName: 'Other Earnings',
        componentCode: 'OTHER_EARNINGS',
        category: SalaryComponentCategory.EARNING,
        sourceType: SalaryComponentSourceType.MANUAL_DEFAULT,
        status: SalaryComponentStatus.ACTIVE,
        defaultEnabled: false,
        calculationType: SalaryCalculationType.FIXED,
        value: 0,
        percentageOf: null,
        formulaExpression: null,
        taxable: true,
        includeInPfWage: false,
        includeInEsiWage: false,
        includeInGross: true,
        affectsNetPay: false,
        editableForEmployee: true,
        displayOrder: 4,
      },
      {
        componentName: 'Additional Recovery',
        componentCode: 'ADDITIONAL_RECOVERY',
        category: SalaryComponentCategory.DEDUCTION,
        sourceType: SalaryComponentSourceType.MANUAL_DEFAULT,
        status: SalaryComponentStatus.ACTIVE,
        defaultEnabled: false,
        calculationType: SalaryCalculationType.FIXED,
        value: 0,
        percentageOf: null,
        formulaExpression: null,
        taxable: false,
        includeInPfWage: false,
        includeInEsiWage: false,
        includeInGross: false,
        affectsNetPay: true,
        editableForEmployee: true,
        displayOrder: 10,
      },
    ],
  };
};
